// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package gateway

import (
	"database/sql"
	"time"
)

type Bottle struct {
	BottleID   string
	PersonID   string
	BottleType string
	VolumeMl   int64
	OccurredAt time.Time
	Notes      string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Diaper struct {
	DiaperID   string
	PersonID   string
	Type       string
	OccurredAt time.Time
	Notes      string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Nurse struct {
	NurseID              string
	PersonID             string
	RightDurationSeconds int64
	LeftDurationSeconds  int64
	RightVolumeMl        int64
	LeftVolumeMl         int64
	StartedAt            time.Time
	EndedAt              time.Time
	Notes                string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Person struct {
	PersonID  string
	Name      string
	BirthDate sql.NullTime
	BirthTime interface{}
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Sleep struct {
	SleepID   string
	PersonID  string
	StartedAt time.Time
	EndedAt   time.Time
	Notes     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Weight struct {
	WeightID     string
	PersonID     string
	WeightOunces int64
	OccurredAt   time.Time
	Notes        string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
